import { StaticPageLayout } from '@/components/static-page-layout'

export default function PrivacyPage() {
  return (
    <StaticPageLayout
      title="Privacy Policy"
      subtitle={`Last updated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' })}`}
    >
      <h2>Information we collect</h2>
      <p>
        We collect information you provide directly, such as your profile
        details, photos, and messages, along with information generated by
        using the app, such as match activity and payment records.
      </p>
      <h2>How we use your information</h2>
      <p>
        We use your information to operate and improve Nuru, match you with
        other users, process payments, keep the platform safe, and
        communicate with you about your account.
      </p>
      <h2>Sharing</h2>
      <p>
        We don&apos;t sell your personal data. We share information with
        service providers (such as payment processors) only as needed to
        operate the app, and with authorities when required by law.
      </p>
      <h2>Your choices</h2>
      <p>
        You can update or delete your profile information at any time from
        your account settings. You can request a full copy or deletion of
        your data by contacting us.
      </p>
      <h2>Contact</h2>
      <p>
        Questions about this policy? Reach us at{' '}
        <a href="mailto:support@gmail.co.ke">support@gmail.co.ke</a>.
      </p>
    </StaticPageLayout>
  )
}
